version: "3"

services:
  frontend:
    image: node:16-alpine
    volumes:
      - ./:/home/node/app/frontend/
    working_dir: /home/node/app/frontend
    command: sh -c 'npm i --include=dev && npm run build'

  api:
    image: node:alpine
    restart: always
    expose:
      - 3000
    volumes:
      - ./api/:/home/node/app/api/
    working_dir: /home/node/app/api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AUTH_USERNAME=
      - AUTH_PASSWORD=
    command: sh -c 'npm i && nodejs index.mjs'

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./dist/:/var/www/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - api
