name: Build and Deploy app

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Frontend
        uses: docker/build-push-action
        with:
          context: .
          file: frontend.Dockerfile
          push: true
          tags: frontend

      - name: Build and push Backend
        uses: docker/build-push-action
        with:
          context: .
          file: backend.Dockerfile
          push: true
          tags: backend
